name: Build macOS .app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: cleanblemacos

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build macOS app
        run: |
          pyinstaller --windowed --name="Cleanable" --icon=buddy_icon.png buddy_app.py

      - name: Zip .app
        run: |
          cd dist
          zip -r Cleanable.zip Cleanable.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleanable-macos-app
          path: cleanblemacos/dist/Cleanable.zip
