name: Build Mac App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
- name: Setup Python 3.10
  uses: actions/setup-python@v4
  with:
    python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build app with PyInstaller
        run: |
          pyinstaller --windowed --name="Cleanable" --icon=cleanable-macos/buddy_icon.icns buddy_app.py
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Cleanable-macos-build
          path: dist/Cleanable.app
