name: Build Cleanable macOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_mac:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build Cleanable app with PyInstaller
        run: |
          pyinstaller --windowed --name="Cleanable" --icon=cleanable-macos/buddy_icon.icns buddy_app.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: cleanable-macos
          path: dist/Cleanable.app
