name: Build Cleanable macOS App

on:
  push:
    branches: [main]
    paths:
      - 'cleanable-macos/**'

jobs:
  build:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: cleanable-macos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build macOS app with PyInstaller
        run: |
          pyinstaller --windowed --name="Cleanable" --icon=buddy_icon.png buddy_app.py

      - name: Zip the built app
        run: |
          cd dist
          zip -r Cleanable.zip Cleanable.app

      - name: Upload Cleanable.app artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleanable-macos-app
          path: dist/Cleanable.zip
