name: Build Mac

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build with PyInstaller
        run: |
          pyinstaller --windowed --name="Cleanable" --icon=cleanable-macos/buddy_icon.icns buddy_app.py
